#!/usr/bin/env bash
#
# One-shot setup script. Idempotent — safe to re-run.
#
# Prepares:
#   .env                   from .env.example, if missing
#   searxng/settings.yml   with a freshly-generated secret_key, if missing
#
# Then brings the stack up via `docker compose up -d --build`.
#
# Usage:
#   ./install.sh           # set up + start
#   ./install.sh --no-up   # set up only, don't start the stack

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

NO_UP=0
for arg in "$@"; do
  case "$arg" in
    --no-up) NO_UP=1 ;;
    -h|--help)
      sed -n '3,15p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required tool: $1" >&2
    exit 1
  }
}

require docker
require openssl

# ---------------------------------------------------------------------------
# 1. .env
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  cp .env.example .env
  echo "Created .env from .env.example."
  echo "Edit .env to fill in TELEGRAM_BOT_TOKEN and ALLOWED_USER_IDS, then re-run."
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. searxng/settings.yml — generate with a fresh secret_key.
#    Never written into the repo; this file is gitignored.
# ---------------------------------------------------------------------------
if [ ! -f searxng/settings.yml ]; then
  if [ -d searxng ] && [ ! -w searxng ]; then
    echo "searxng/ exists but is not writable by you (probably owned by the SearXNG container UID)." >&2
    echo "Take ownership first:  sudo chown -R \"\$(id -u):\$(id -g)\" searxng" >&2
    exit 1
  fi
  mkdir -p searxng
  SEARXNG_SECRET="$(openssl rand -hex 32)"
  cat > searxng/settings.yml <<EOF
use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - bing
      - wikipedia
      - wikidata
      - mojeek
      - qwant

server:
  # Internal-only service on the docker network; not exposed to the host.
  # secret_key generated by install.sh and kept out of git.
  secret_key: "${SEARXNG_SECRET}"
  limiter: false
  image_proxy: false
  bind_address: "0.0.0.0"
  port: 8080

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json

general:
  instance_name: "local-bot-search"
  debug: false
EOF
  echo "Generated searxng/settings.yml with a fresh secret_key."
fi

# ---------------------------------------------------------------------------
# 3. Bring up the stack.
# ---------------------------------------------------------------------------
if [ "$NO_UP" -eq 1 ]; then
  echo "Setup complete. Skipping 'docker compose up' (--no-up)."
  exit 0
fi

echo "Starting docker compose..."
exec docker compose up -d --build
